# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=250)),
                ('height', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=250)),
                ('routine', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='authorsindexpage',
            name='routine',
        ),
        migrations.AddField(
            model_name='authorsindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
