# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20170613_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpage',
            name='name',
        ),
    ]
