# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_authorpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='instagram',
            field=models.CharField(default='instagram.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorpage',
            name='myfitnesspal',
            field=models.CharField(default='myfitnesspal.com', max_length=250),
            preserve_default=False,
        ),
    ]
